import Head from "next/head";
import { Navbar } from "../../components/Navbar";
import { teamImages } from "@/data/teamImages";

const AboutUs = () => {
  return (
    <>
      <Head>
        <title> About Us | RKS </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/rks-logo.png" />
      </Head>

      <Navbar />
      <div>
        <div className=" my-4 mt-20 py-12">
          <div className="mx-auto max-w-[1350px]">
            <div className="flex flex-col items-center md:flex-row">
              <div className="w-full px-6 md:w-1/2 md:max-w-[610px] xl:px-0">
                <img
                  src="our-story.png"
                  alt="About FundImpact"
                  className="w-full rounded-lg h-80"
                />
              </div>
              <div className="mx-auto w-full flex-col items-center justify-center px-6 md:w-1/2 lg:max-w-[650px] xl:ml-28 xl:px-0">
                <p className="mb-2 mt-6 text-2xl font-semibold text-[#FF7A00] sm:text-3xl lg:mb-2 lg:mt-1 lg:text-4xl">
                  Our Story
                </p>
                <p className="mt-4 mr-6 text-sm font-light text-gray-800  sm:text-base lg:text-lg xl:px-0">
                  Founded by a team of automotive enthusiasts with years of
                  industry expertise, RKS was born from the recognition of a
                  need within the Philippine market. We understand the
                  challenges and uncertainties individuals face when navigating
                  the process of purchasing or selling a used car. Hence, RKS
                  was conceptualized to bridge these gaps and provide a
                  seamless, informed, and secure platform for all involved.
                </p>
              </div>
            </div>
          </div>
        </div>

        <div className="mx-auto mt-6 max-w-[1350px] md:mb-12">
          <div className="flex flex-col-reverse items-center md:flex-row">
            <div className=" w-full flex-col items-center justify-center md:w-1/2">
              <p className="mb-2 mt-4 px-6 text-2xl font-semibold text-[#FF7A00] sm:text-3xl md:mt-0 lg:text-4xl xl:px-0">
                Join the RKS Community
              </p>
              <p className="mt-4 mb-4 px-6 text-sm font-light text-gray-800 sm:text-base md:max-w-[620px] lg:text-lg xl:px-0">
                Join us in our mission to revolutionize the second-hand car
                market in the Philippines. We invite you to explore our
                platform, engage with our Predict Price feature powered by our
                cutting-edge algorithm, and experience the ease and reliability
                that RKS offers. Together, let's make informed choices and drive
                towards a future of trust and satisfaction in the automotive
                industry.
              </p>
            </div>
            <div className="w-full px-6 md:w-1/2 md:max-w-[650px] xl:ml-8 xl:px-0">
              <img
                src="rks-community.png"
                alt="Mission"
                className="w-full rounded-lg h-80"
              />
            </div>
          </div>
        </div>

        <div className=" flex flex-col items-center justify-center">
          <div className="mb-10 mt-10 text-4xl font-medium text-[#FF7A00] md:text-5xl">
            Meet Our Team
          </div>
          <div className="mb-12 flex items-center justify-center">
            <ul className="grid grid-cols-1 gap-20 sm:grid-cols-1 md:grid-cols-1 lg:grid-cols-3 xl:grid-cols-3">
              {teamImages.map((member, index) => (
                <li
                  key={index}
                  className="duration-400 group relative h-96 w-64 transform items-center justify-center transition ease-in-out hover:-translate-y-1 hover:scale-105"
                >
                  <div className="absolute inset-0 flex flex-col items-center justify-center">
                    <img
                      src={member.image}
                      className="h-96 w-full rounded-lg shadow-lg"
                      alt={member.name}
                    />
                    <div className="absolute bottom-0 w-full bg-gray-800 bg-opacity-60 p-1 opacity-0 group-hover:opacity-100">
                      <div className="ml-2 text-center text-lg font-medium tracking-tight text-white">
                        {member.name}
                      </div>
                    </div>
                  </div>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>
    </>
  );
};

export default AboutUs;
