import Head from "next/head";
import { Navbar } from "../../components/Navbar";
import { useState } from "react";
import Dropdown from "@/components/Dropdown";

const CheckCarPrice = () => {
  const [selectedBrand, setSelectedBrand] = useState("Select Car Brand");

  const handleBrandSelection = (brand: string) => {
    setSelectedBrand(brand);
  };

  return (
    <>
      <Head>
        <title> Check Car Price | RKS </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/rks-logo.png" />
      </Head>

      <Navbar />

      <div
        className="bg-contain min-h-screen flex justify-center items-center"
        style={{
          backgroundImage: "url('hero-bg.png')",
          backgroundSize: "100% 100%",
        }}
      >
        <div className="max-w-[1350px]">
          <div className="text-white pt-24 flex-col text-center">
            <div className="md:text-4xl text-2xl sm:text-3xl font-semibold uppercase">
              Check your <span className="text-[#FF7A00] mr-2">car price</span>
              and know its value
            </div>

            <div className="bg-white w-[1350px] h-[500px] rounded-2xl shadow mt-8">
              <div className="flex-col pt-8 text-left ml-8 font-medium text-gray-800">
                Brand of your Car
                <Dropdown
                  width="80"
                  label={selectedBrand}
                  options={["Toyota", "Geely", "Honda"]}
                  onSelect={handleBrandSelection}
                  optionWidth="80"
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default CheckCarPrice;
