import Head from "next/head";
import { Navbar } from "../../components/Navbar";
import { HeroSection } from "./HeroSection";
import { AboutSection } from "./AboutSection";
import { CarBrands } from "./CarBrands";
import { Footer } from "@/components/Footer";

const Home = () => {
  return (
    <>
      <Head>
        <title> RKS </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/rks-logo.png" />
      </Head>

      <Navbar/>
      <HeroSection />
      <AboutSection />
      <CarBrands />
      <Footer />
      
    </>
  );
};

export default Home;