import Head from "next/head";
import { Navbar } from "../../components/Navbar";
import { usedCars } from "@/data/usedCars";
import { IoLocationSharp } from "react-icons/io5";
import FilterByCategory from "@/components/Filter";
import { RiSearchLine } from "react-icons/ri";
import { useState, SetStateAction } from "react";

const UsedCars = () => {
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedCategory, setSelectedCategory] = useState("Categories");
  const [isCategoryListOpen, setIsCategoryListOpen] = useState(false);

  const toggleCategoryList = () => {
    setIsCategoryListOpen(!isCategoryListOpen);
  };

  const handleCategorySelect = (category: SetStateAction<string>) => {
    setSelectedCategory(category);
    setIsCategoryListOpen(false);
  };

  return (
    <>
      <Head>
        <title> Used Cars | RKS </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/rks-logo.png" />
      </Head>

      <Navbar />
      <div className="max-w-[1235px] mx-auto mt-36 flex items-center justify-between">
        <div className="relative flex items-center">
          {" "}
          <FilterByCategory
            selectedCategory={selectedCategory}
            isCategoryListOpen={isCategoryListOpen}
            toggleCategoryList={toggleCategoryList}
            handleCategorySelect={handleCategorySelect}
          />
        </div>

        <div className="relative ml-auto">
          <input
            type="text"
            placeholder="Search"
            className="w-96 rounded-md border border-gray-600 py-2 pl-8 pr-4"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
          />
          <RiSearchLine
            className="absolute left-2 top-3 text-gray-500"
            size={20}
          />
        </div>
      </div>

      <div className="mt-6 mb-2 flex items-center justify-center">
        <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-4">
          {usedCars
            .filter(
              (card) =>
                selectedCategory === "Categories" ||
                card.brand === selectedCategory
            )
            .filter((card) =>
              card.name.toLowerCase().includes(searchQuery.toLowerCase())
            )
            .map((card, index) => (
              <div
                key={index}
                className="w-full transform justify-self-start rounded-lg border border-gray-200 bg-white font-medium shadow transition duration-500 ease-in-out hover:-translate-y-1 hover:scale-105 dark:bg-white"
              >
                <img
                  className="h-52 w-72 rounded-t-lg"
                  src={card.image}
                  alt={card.name}
                />

                <div className="p-4">
                  <div className="card-title">
                    <div className="text-base tracking-tight text-gray-900">
                      {card.name}
                    </div>
                  </div>

                  <div className="text-lg ml-1 text-[#FF7A00]">
                    ₱{card.price}
                  </div>

                  <div className="flex flex-row items-center font-normal text-gray-800 dark:text-gray-500 text-sm">
                    <IoLocationSharp size={15} /> {card.location}
                  </div>
                </div>
              </div>
            ))}
        </div>
      </div>
    </>
  );
};

export default UsedCars;
